custom:
  names:
    dynamodbTable: serverless-localstack-monorepo-${self:provider.stage}
  webpack:
    webpackConfig: '../../../webpack.config.js'
    packager: 'yarn'
    keepOutputDirectory: true
  localstack:
    stages:
      - local
    host: http://localhost
    autostart: true
    lambda:
      mountCode: true
    debug: false
