custom:
  names:
    dynamodbTable: serverless-localstack-monorepo-${self:provider.stage}
    sqsQueue: serverless-localstack-monorepo-${self:provider.stage}
  webpack:
    webpackConfig: '../../../webpack.config.js'
    packager: 'yarn'
    keepOutputDirectory: true
  localstack:
    stages:
      - local
    host: http://localhost
    autostart: true
    lambda:
      mountCode: true
    debug: false

apiGateway:
  restApiId:
    Fn::ImportValue: serverless-localstack-monorepo-${self:provider.stage}-id
  restApiRootResourceId:
    Fn::ImportValue: serverless-localstack-monorepo-${self:provider.stage}-root-resource-id
  restApiResources:
    items:
      Fn::ImportValue: serverless-localstack-monorepo-${self:provider.stage}-items-resource-id
    queues:
      Fn::ImportValue: serverless-localstack-monorepo-${self:provider.stage}-queues-resource-id
