- Effect: Allow
  Action:
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
  # Restrict our IAM role permissions to
  # the specific table for the stage
  Resource:
    - 'Fn::GetAtt': [ItemsTable, Arn]
