Resources:
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.names.dynamodbTable}
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: password
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: password
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
